#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

replace_icon() {
	iconSource=$2
	iconDestination=$1
	icon=/tmp/`basename $iconSource`
	rsrc=/tmp/icon.rsrc
	
	# Create icon from the iconSource
	cp $iconSource $icon
	
	# Add icon to image file, meaning use itself as the icon
	sips -i $icon
	
	# Take that icon and put it into a rsrc file
	DeRez -only icns $icon > $rsrc

	# Apply the rsrc file to
	SetFile -a C "$iconDestination"

	if [[ -f $iconDestination ]]; then
		# Destination is a file
		Rez -append $rsrc -o "$iconDestination"
	elif [[ -d $iconDestination ]]; then
		# Destination is a directory
		# Create the magical Icon\r file
		touch $iconDestination/$'Icon\r'
		Rez -append $rsrc -o $iconDestination/Icon?
		SetFile -a V $iconDestination/Icon?
	fi
}

set_icon() {
	if [[ -a "$DIR/BrowserIconsSrc/$2.png" && ! -a "$DIR/BrowserIcons/$2.icns" ]]; then
		echo "png"
		echo "sips -s format icns \"$DIR/BrowserIconsSrc/$2.png\" --out \"$DIR/BrowserIcons/$2.icns\""
		sips -s format icns "$DIR/BrowserIconsSrc/$2.png" --out "$DIR/BrowserIcons/$2.icns"
	fi
	
	if [[ -a "$path/Contents/Resources/$2.icns" ]]; then
		replace_icon "/Applications/Browsers/$1" "$path/Contents/Resources/$2.icns"
	elif [[ -a "$DIR/BrowserIcons/$2.icns" ]]; then
		replace_icon "/Applications/Browsers/$1" "$DIR/BrowserIcons/$2.icns"
	fi
}

# http://hintsforums.macworld.com/archive/index.php/t-18644.html
make_alias() {
	src=$1
	dir=$(dirname "$2")
	file=$(basename "$2")
	rm -rf "$2"
	/usr/bin/osascript -e "tell application \"Finder\"" -e "set macSrcPath to POSIX file \"$src\" as alias" -e "set macDestPath to POSIX file \"$dir\" as alias" -e "make new alias file to macSrcPath at folder macDestPath" -e "set name of result to \"$file\"" -e "end tell"
}

app() {
	path="/Applications/$1.app"
	alias_path="$folder/$2"
	if [[ -a $path ]]; then
		echo "[x] $2"
		make_alias "$path" "$alias_path"
		set_icon "$2" "$3"
	else
		echo "[ ] $2 ($path)"
	fi
}

vbox() {
	alias_path="$folder/$2"
	if [[ -a $1 ]]; then
		echo "[x] $2 [VirtualBox]"
		make_alias "$1" "$alias_path"
		set_icon "$2" "$3"
	else
		echo "[ ] $2 ($1) [VirtualBox]"
	fi
}

vmware() {
	path="$1.vmwarevm"
	alias_path="$folder/$2"
	if [[ -a $path ]]; then
		echo "[x] $2 [VMWare]"
		make_alias "$path" "$alias_path"
		set_icon "$2" "$3"
	else
		echo "[ ] $2 ($path) [VMWare]"
	fi
}

# Folders
folder="/Applications/Browsers"

replace_icon $folder "$DIR/BrowserFolderIcon/BrowserFolderIcon.icns"
mkdir -p "$folder/BlackBerry"
replace_icon "$folder/BlackBerry" "$DIR/BrowserIcons/BlackBerry.icns"
mkdir -p "$folder/Chrome"
replace_icon "$folder/Chrome" "$DIR/BrowserIcons/Chrome.icns"
mkdir -p "$folder/IE"
replace_icon "$folder/IE" "$DIR/BrowserIcons/IE.icns"
mkdir -p "$folder/Firefox"
replace_icon "$folder/Firefox" "$DIR/BrowserIcons/Firefox.icns"
mkdir -p "$folder/Opera"
replace_icon "$folder/Opera" "$DIR/BrowserIcons/Opera.icns"

# Get VM folder
vmdir="/Users/$USER/Virtual Machines"
#vmdir="/Users/$USER/.ievms"

echo "---> Generating App Aliases"
app "Android"				"Android"	"Android"

vmware "$vmdir/BlackBerry10Simulator-BB10_1_X"			"BlackBerry/BlackBerry 10"			"BlackBerry"
vmware "$vmdir/BlackBerryPlayBookSimulator-2.1.0"		"BlackBerry/BlackBerry PlayBook"	"BlackBerry"

app "BrowserStack"				"BrowserStack"			"BrowserStack"
app "Chromium"					"Chrome/Chromium"		"app"
app "Google Chrome Canary"		"Chrome/Chrome Canary"	"app"
app "Google Chrome"				"Chrome/Chrome"			"app"
app "Firefox"					"Firefox/Firefox"				"firefox"
app "FirefoxAurora"				"Firefox/Firefox Aurora"		"firefox"
app "FirefoxNightly"			"Firefox/Firefox Nightly"		"firefox"
app "B2G"						"Firefox/Boot2Gecko"		"b2g"

vbox "$vmdir/IE6 - WinXP.ova"			"IE/IE6 - WinXP"	"IE6"
vbox "$vmdir/IE7 - WinXP.ova"			"IE/IE7 - WinXP"	"IE7"
vbox "$vmdir/IE8 - WinXP.ova"			"IE/IE8 - WinXP"	"IE8"
vbox "$vmdir/IE9 - Win7.ova"			"IE/IE9 - Win7"		"IE9"
vbox "$vmdir/IE10 - Win7.ova"			"IE/IE10 - Win7"	"IE10"
vbox "$vmdir/IE11 - Win7.ova"			"IE/IE11 - Win7"	"IE11"

vbox "/Users/$USER/.ievms/IE6 - WinXP.ova"			"IE/IE6 - WinXP"	"IE6"
vbox "/Users/$USER/.ievms/IE7 - WinXP.ova"			"IE/IE7 - WinXP"	"IE7"
vbox "/Users/$USER/.ievms/IE8 - WinXP.ova"			"IE/IE8 - WinXP"	"IE8"
vbox "/Users/$USER/.ievms/IE9 - Win7.ova"			"IE/IE9 - Win7"		"IE9"
vbox "/Users/$USER/.ievms/IE10 - Win7.ova"			"IE/IE10 - Win7"	"IE10"
vbox "/Users/$USER/.ievms/IE11 - Win7.ova"			"IE/IE11 - Win7"	"IE11"

vmware "$vmdir/IE6.XP.For.MacVMware"				"IE/IE6 (WinXP)"		"IE6"
vmware "$vmdir/IE7.Vista.For.MacVMware"				"IE/IE7 (WinVista)"		"IE7"
vmware "$vmdir/IE8.Win7.For.MacVMware"				"IE/IE8 (Win7)"			"IE8"
vmware "$vmdir/IE8.WinXP.For.MacVMware"				"IE/IE8 (WinXP)"		"IE8"
vmware "$vmdir/IE9.Win7.For.MacVMware"				"IE/IE9 (Win7)"			"IE9"
vmware "$vmdir/IE10.Win7.For.MacVMware"				"IE/IE10 (Win7)"		"IE10"
vmware "$vmdir/IE10.Win8.For.MacVMware"				"IE/IE10 (Win8)"		"IE10"
vmware "$vmdir/IE11.Win7.For.MacVMware"				"IE/IE11 (Win7)"		"IE11"
vmware "$vmdir/IE11.Win8.1Preview.For.MacVMware"	"IE/IE11 (Win8.1)"		"IE11"

app "Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/iOS Simulator"		"iOS"
app "Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone Simulator"		"iOS"

app "Opera"						"Opera/Opera"
app "Opera Mobile Emulator"		"Opera/Opera Mobile"
app "Opera Next"				"Opera/Opera Next"
app "PhantomJS"					"PhantomJS"				"PhantomJS"
app "Safari"					"Safari"
app "Sauce"						"Sauce"
app "TorBrowser"				"TorBrowser"
